name: CI para Taller Web I
run-name: "CI/CD: Validando Pull Request"
on:
  pull_request:
    branches: ["main"]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el codigo
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Correr Pruebas
        run: mvn -B verify --file pom.xml

      - name: Publicar Reporte de Pruebas
        uses: actions/upload-artifact@v3
        with:
          name: Surefire report
          path: target/surefire-reports
